# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21c71f841fc4cc6080556461cd340f7e143e1c4bb9cb6f9773893061a245a1a4e21de2f230ffdfbfab485cd7e4ed968a7b768df900c056429569efc38683cf6c

test:
  secret_key_base: 57fa21818f6e00fc8ccaf5d6164edaf61829c5effd5b6d723f0677f36561f809de0a3444157d8ab168f23d458e354d5797a3e7b906ab1ca0ac9fcf2007965a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
